'remote_theme: pages-themes/minimal@v0.2.0
'plugins:
'- jekyll-remote-theme # add this line to the plugins list if you already have one

'title: Maya Bian 
'description: Princeton in Asia Fellow at Population Services International, Vientiane, Laos

'maya.al.bian@gmail.com | GitHub | LinkedIn | Resume

title: Minimal theme
'logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
'show_downloads: true
'google_analytics:
'theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
