
title: Maya Bian 
description: Princeton in Asia Fellow at Population Services International in Vientiane, Laos <p><small>ma.al.bian@gmail.com | <a href="https://https://www.linkedin.com/in/maya-bian/">LinkedIn</a> | Resume </small></p> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

