title: <b>Maya Bian</b>
description: Maya is a <a href="https://piaweb.princeton.edu/">Princeton in Asia</a> Fellow at <a href ="https://www.psilaos.org/">Population Services International</a> in Vientiane, Laos <small><p>maya.al.bian@gmail.com | <a href="https://github.com/malbian">Github</a> | <a href="https://www.linkedin.com/in/maya-bian/">LinkedIn</a> | <a href="https://malbian.github.io/files/Githubresume.pdf" target="_blank">Resume</a></p></small> 
logo: /img/profile.JPG
remote_theme: pages-themes/minimal@v0.2.0
github:
  is_user_page: false 
  is_project_page: false
footer: none
google_analytics: G-WR8E49XTVT
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
